# version: "3.1"
# services:

#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: password
 

version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3305'
    volumes:
      - my-db:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment: 
      ADMINER_DEFAULT_SERVER: db
    ports: 
      - 8080:8080
volumes:
  my-db: